Nivra/Controllers/CommonController.cs
using Microsoft.AspNetCore.Mvc;
using Nivara.Core.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nivara.Web.Controllers
{
    public class CommonController : Controller
    {
        private readonly ICommonServices _commonServices;
        public CommonController(ICommonServices commonServices)
        {
            _commonServices = commonServices;
        }
        public async Task<IActionResult> GetStatesByCountryId(int id=0)
        {
            var states = await _commonServices.GetStatesByCountryId(id);
            return Json(states);
        }

        public async Task<IActionResult> GetCitiesByStateId(int id = 0)
        {
            var cities = await _commonServices.GetCitiesByStateId(id);
            return Json(cities);
        }
    }
}

Nivra/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Nivara.Common.Constants;
using Nivara.Common.Helpers;
using Nivara.Core.Common;
using Nivara.Core.CompanyDetail;
using Nivara.Core.CompanyRole;
using Nivara.Core.Employee;
using Nivara.Models;
using Nivara.Web.Helper;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Nivara.Web.Controllers
{
    [Authorize]
    public class EmployeeController : BaseController
    {
        private readonly IEmployeeServices _employeeServices;
        private readonly ICommonServices _commonServices;
        private readonly ICompanyRolesServices _companyRolesServices;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IOptions<AppSettingsModel> options;
        public EmployeeController(IEmployeeServices employeeServices, ICommonServices commonServices, ICompanyRolesServices companyRolesServices, IWebHostEnvironment hostEnvironment, IOptions<AppSettingsModel> _options)
        {
            _employeeServices = employeeServices;
            _commonServices = commonServices;
            _companyRolesServices = companyRolesServices;
            _webHostEnvironment = hostEnvironment;
            options = _options;
        }

        public async Task<IActionResult> Index()
        {
            ShowPassMessage();
            List<EmployeeModel> model = new List<EmployeeModel>();
            try
            {
                model = await _employeeServices.GetEmployeesByCompanyId(HttpContext.Session.GetComplexData<int>(SessionConstants.CompanyId));

            }
            catch (Exception ex)
            {

            }
            return View(model);
        }
        public  ActionResult GetData(JqueryDatatableParam param)
        {
            var employees =  _employeeServices.GetEmployeesByCompanyId(HttpContext.Session.GetComplexData<int>(SessionConstants.CompanyId));


            //employees.ToList().ForEach(x => x.StartDateString = x.StartDate.ToString("dd'/'MM'/'yyyy"));

            if (!string.IsNullOrEmpty(param.sSearch))
            {
                //employees = employees.Where(x => x.UserName.ToLower().Contains(param.sSearch.ToLower()));
                                             // || x.Position.ToLower().Contains(param.sSearch.ToLower())
                                             // || x.Location.ToLower().Contains(param.sSearch.ToLower())
                                            //  || x.Salary.ToString().Contains(param.sSearch.ToLower())
                                            //  || x.Age.ToString().Contains(param.sSearch.ToLower())
                                             // || x.StartDate.ToString("dd'/'MM'/'yyyy").ToLower().Contains(param.sSearch.ToLower())).ToList();
            }

            //var sortColumnIndex = Convert.ToInt32(HttpContext.Request.QueryString["iSortCol_0"]);
            //var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];

            //if (sortColumnIndex == 3)
            //{
            //    employees = sortDirection == "asc" ? employees.OrderBy(c => c.Age) : employees.OrderByDescending(c => c.Age);
            //}
            //else if (sortColumnIndex == 4)
            //{
            //    employees = sortDirection == "asc" ? employees.OrderBy(c => c.StartDate) : employees.OrderByDescending(c => c.StartDate);
            //}
            //else if (sortColumnIndex == 5)
            //{
            //    employees = sortDirection == "asc" ? employees.OrderBy(c => c.Salary) : employees.OrderByDescending(c => c.Salary);
            //}
            //else
            //{
            //    Func<Employee, string> orderingFunction = e => sortColumnIndex == 0 ? e.Name :
            //                                                   sortColumnIndex == 1 ? e.Position :
            //                                                   e.Location;

            //    employees = sortDirection == "asc" ? employees.OrderBy(orderingFunction) : employees.OrderByDescending(orderingFunction);
            //}

            //var displayResult = employees.Skip(param.iDisplayStart)
            //    .Take(param.iDisplayLength).ToList();
            //var totalRecords = employees.Count();

            return Json(new
            {
                //param.sEcho,
                //iTotalRecords = totalRecords,
                //iTotalDisplayRecords = totalRecords,
                //aaData = displayResult
            });

        
    }
        
        public async Task<ActionResult> Employee_Read()
        {
            //var length = Request.Form["length"].FirstOrDefault();
            //var data = await _employeeServices.GetEmployeesByCompanyId(HttpContext.Session.GetComplexData<int>(SessionConstants.CompanyId));

            //return Ok(data);

            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() +
                                              "][name]"].FirstOrDefault();
                var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
                var searchValue = Request.Form["search[value]"].FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int recordsTotal = 0;
                var customerData = await _employeeServices.GetEmployeesByCompanyId(HttpContext.Session.GetComplexData<int>(SessionConstants.CompanyId));

                //if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDirection)))
                //{
                //    customerData = customerData.OrderBy(sortColumn + " " + sortColumnDirection);
                //}
                //if (!string.IsNullOrEmpty(searchValue))
                //{
                //    customerData = customerData.Where(m => m.FirstName.Contains(searchValue)
                //                        || m.LastName.Contains(searchValue)
                //                        || m.Contact.Contains(searchValue)
                //                        || m.Email.Contains(searchValue));
                //}
                recordsTotal = customerData.Count();
                var data = customerData.Skip(skip).Take(pageSize).ToList();
                var jsonData = new
                {
                    draw = draw,
                    recordsFiltered = recordsTotal,
                    recordsTotal = recordsTotal,
                    data = data
                };
                return Ok(jsonData);
            }
            catch (Exception ex)
            {
                throw;
            }

        }

        [HttpGet]
        public async Task<IActionResult> Manage(string id)
        {
            ShowPassMessage();
            EmployeeModel model = new EmployeeModel();

            if (!string.IsNullOrEmpty(id))
            {
                var eId = Convert.ToInt32(id);//Convert.ToInt32(SecurityHelper.Decrypt(id));
                model = await _employeeServices.GetEmployeeById(eId);
                model.States = await _commonServices.GetStatesByCountryId(model.CountryId);
                model.Cities = await _commonServices.GetCitiesByStateId(model.StateId);
                model.EncrytedId = id;
                model.Id = eId;
                model.EmpId = eId;
            }

            model.Countries = await _commonServices.GetCountries();
            //model.CompanyRoles = await _companyRolesServices.GetRolesByCompanyId(HttpContext.Session.GetComplexData<int>(SessionConstants.CompanyId));
            model.Titles = Common.StaticMethod.Common.CreateDropDownForName<Common.Enums.TitlesEnum>();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Manage(EmployeeModel model)
        {
            try
            {
                model.Id = model.EmpId; //Convert.ToInt32(SecurityHelper.Decrypt(model.EncrytedId));
                string uniqueFileName = UploadedFile(model);
                model.ProfilePicture = uniqueFileName;
                model.CompanyId = HttpContext.Session.GetComplexData<int>(SessionConstants.CompanyId);
                model.CreatedBy = HttpContext.Session.GetComplexData<string>(SessionConstants.UserId);
                model.ModifiedBy = model.CreatedBy;
                await _employeeServices.ManageEmployee(model);
                SuccessPassMessage(MessageConstants.SavedSuccessfully);
            }
            catch (Exception ex)
            {
                model.Countries = await _commonServices.GetCountries();
                model.States = await _commonServices.GetStatesByCountryId(model.CountryId);
                model.Cities = await _commonServices.GetCitiesByStateId(model.StateId);
                //model.CompanyRoles = await _companyRolesServices.GetRolesByCompanyId(HttpContext.Session.GetComplexData<int>(SessionConstants.CompanyId));
                model.Titles = Common.StaticMethod.Common.CreateDropDownForName<Common.Enums.TitlesEnum>();
                FailMessage(ex.Message);
                return View(model);
            }
            return RedirectToAction("Index");
        }


        private string UploadedFile(EmployeeModel model)
        {
            string uniqueFileName = null;

            if (model.ProfileImage != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfileImage.FileName;

Nivra/Views/Employee/Dashboard.cshtml
@model List<Nivara.Models.EmployeesTaskModel>

@{
    ViewBag.Title = "Dashboard";
}

@*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@

<!-- Start Content-->
<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <a href="@Url.Action("Manage","Employee")" id="addEmployee" class="page-title" style="float:right"> <i class="mdi mdi-plus-box-multiple"></i>&nbsp; Add Employee</a>
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->


    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="tab-pane show active" id="basic-datatable-preview">
                        <table id="basic-datatable" class="table dt-responsive nowrap w-100">
                            <thead>
                                <tr>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Task
                                    </th>

                                    <th>
                                        Action
                                    </th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.EmployeeName
                                        </td>
                                        <td>
                                            @item.TaskName
                                        </td>

                                        <td>
                                            <a href="@Url.Action("Manage","UsersTask",new { @id=""+item.TaskId+""})"> View</a>
                                            <a href="#" data-task="@item.TaskId" data-receiver="@item.AspNetUserId" class="createTaskChat"> Chat</a>
                                        </td>
                                    </tr>

                                }

                                <tr>
                                    <td>
                                        Chandra
                                    </td>
                                    <td>
                                        TestTask
                                    </td>

                                    <td>
                                        <a href="@Url.Action("Manage","UsersTask",new { @id=""+123+""})"> View</a>
                                        <a href="#" data-task="123" data-receiver="123" class="createTaskChat"> Chat</a>
                                    </td>
                                </tr>
                            </tbody>

                        </table>
                    </div> <!-- end preview-->
                </div> <!-- end card body-->
            </div> <!-- end card -->
            <partial name="~/Views/Chat/_ChatPartialView.cshtml" />
        </div><!-- end col-->
    </div>
    <!-- end row-->
</div>
<script>
    $(".createTaskChat").click(function () {
        CreateTaskChat($(this).attr("data-task"), $(this).attr("data-receiver"));
    })

</script>
@*<script>
    $("#addEmployee").click(function () {
        $(".nivaraLoader").show();
    })
    $(".editEmp").click(function () {
        $(".nivaraLoader").show();
    })

    function DeleteEmployee(id) {
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this  record!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {
                    $(".nivaraLoader").show();
             $.ajax({
                 url: '@Url.Action("Delete", "Employee")',
                 data: { id: id },
                datatype: "json",
                type: "get",
                contenttype: 'application/json',
                async: true,
                 success: function (data) {
                     $(".nivaraLoader").hide();
                     if (data.result)
                         window.location = data.url;
                     else
                         swal("Something went wrong!");
                },
                 error: function (res) {
                     $(".nivaraLoader").hide();
                     swal("Something went wrong!");
                }
            });

                }
                //else {
                //    swal("Your imaginary file is safe!");
                //}
            });
    }
</script>*@

Nivra/Views/Employee/Manage.cshtml
@model Nivara.Models.EmployeeModel
@{
    ViewBag.Title = "Manage Employee";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">@ViewBag.Title</h4>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    @using (Html.BeginForm("Manage", "Employee", FormMethod.Post, new { @class = "needs-validation mb-4", role = "form", enctype = "multipart/form-data", @novalidate = "true" }))
                    {
                        @Html.HiddenFor(x => x.EncrytedId)
                        @*@Html.HiddenFor(x => x.Id)*@
                        @Html.HiddenFor(x => x.EmpId)
                        <div class="row form-group">
                            <div class="col-md-12">
                                <div class="form-group">
                                    @if (Model.ProfilePicture != null)
                                    {
                                        <img class="rounded-circle avatar-lg" id="ProfilePicture" src="~/images/@Model.ProfilePicture"
                                             height="100" width="100"
                                             asp-append-version="true" />
                                    }
                                    else
                                    {
                                        <img id="ProfilePicture" class="rounded-circle"
                                             height="100" width="100" src="~/Content/img/avatar.png">
                                    }

                                    <div class="form-group">
                                        <input type="file"
                                               accept=".png,.jpg,.jpeg,.gif,.tif"
                                               asp-for="ProfileImage"
                                               class="form-control"
                                               style="border:0px!important;padding: 0px;padding-top: 10px;padding-bottom: 30px;"
                                               onchange="document.getElementById('ProfilePicture').src = window.URL.createObjectURL(this.files[0])" />
                                    </div>
                                </div>
                            </div>
                            <div class="row col-md-12">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.DropDownListFor(model => model.Prefix, new SelectList(Model.Titles), new { @class = "form-control", @required = "true" })
                                        @Html.ValidationMessageFor(m => m.Prefix, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control", @placeholder = "First Name" })
                                        @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.TextBoxFor(x => x.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            @if (Model.EmpId == 0)
                            {
                                <div class="row col-md-12">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @placeholder = "Your Email", @required = "true" })
                                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            @Html.PasswordFor(x => x.Password, new { @class = "form-control", @placeholder = "Password", @required = "true" })
                                            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control", @placeholder = "ConfirmPassword", @required = "true" })
                                            @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                            }
                            <div class="row col-md-12">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.TextBoxFor(x => x.Address, new { @class = "form-control", @placeholder = "Address" })
                                        @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.TextBoxFor(x => x.PostalCode, new { @class = "form-control", @placeholder = "Postal Code" })
                                        @Html.ValidationMessageFor(m => m.PostalCode, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.TextBoxFor(x => x.ContactNumber, new { @class = "form-control", @placeholder = "Contact Number", maxlength = 12})
                                        @Html.ValidationMessageFor(m => m.ContactNumber, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row col-md-12">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.DropDownListFor(model => model.CountryId, new SelectList(Model.Countries, "Id", "Name"), "Choose Country", new { @class = "form-control", @required = "true" })
                                        @Html.ValidationMessageFor(z => z.CountryId, null, new { @class = "invalid-feedback" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.DropDownListFor(model => model.StateId, new SelectList(Model.States, "Id", "Name"), "Choose State", new { @class = "form-control", @required = "true" })
                                        @Html.ValidationMessageFor(z => z.StateId, null, new { @class = "invalid-feedback" })
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        @Html.DropDownListFor(model => model.CityId, new SelectList(Model.Cities, "Id", "Name"), "Choose City", new { @class = "form-control", @required = "true" })
                                        @Html.ValidationMessageFor(z => z.CityId, null, new { @class = "invalid-feedback" })
                                    </div>
                                </div>
                            </div>
                            <div class="row col-md-12">
                                <div class="col-md-6">
                                    @if (Model.EmpId > 0)
                                    {
                                        <div class="form-group">
                                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control", @placeholder = "Your Email", @readonly = "readonly" })
                                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                        </div>
                                    }
                                </div>
                                @*<div class="col-md-6">
                                    <div class="form-group">
                                        @Html.DropDownListFor(model => model.CompanyRoleId, new SelectList(Model.CompanyRoles, "Id", "Name"), "Choose Role", new { @class = "form-control", @required = "true" })
                                        @Html.ValidationMessageFor(z => z.CompanyRoleId, null, new { @class = "invalid-feedback" })
                                    </div>
                                </div>*@
                            </div>
                            <div class="row col-md-12">
                                <div class="col-md-12 d-grid" style="text-align:center;margin-top:30px;">
                                    <button type="submit" id="submitBtn" style="border-radius: 10px; width: 12%" class="btn btn-xl btn-info">Submit</button>
                                </div>

                            </div>

                        </div>

                    }

                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $("#submitBtn").click(function () {
        $(".nivaraLoader").show();
    })

    $(document).ready(function () {
        $('#CountryId').change(function () {
            $(".nivaraLoader").show();
            var countryId = $('#CountryId').val();
             $.ajax({
                url: '@Url.Action("GetStatesByCountryId", "Common")',
                 data: { id: countryId},
                datatype: "json",
                type: "get",
                contenttype: 'application/json',
                async: true,
                 success: function (data) {
                     var option = "<option>Choose State</option>";
                     $.each(data, function (index, value) {
                         option += '<option value="' + value.id + '">' + value.name + '</option>';
                     });
                     $('#StateId').html(option);
                     $(".nivaraLoader").hide();
                },
                 error: function (res) {
                     $(".nivaraLoader").hide();
                }
            });
        });

         $('#StateId').change(function () {
             var stateId = $('#StateId').val();
             $(".nivaraLoader").show();
             $.ajax({
                url: '@Url.Action("GetCitiesByStateId", "Common")',
                 data: { id: stateId},
                datatype: "json",
                type: "get",
                contenttype: 'application/json',
                async: true,
                 success: function (data) {
                     var option = "<option>Choose City</option>";
                     $.each(data, function (index, value) {
                         option += '<option value="' + value.id + '">' + value.name + '</option>';
                     });
                     $('#CityId').html(option);
                     $(".nivaraLoader").hide();
                },
                 error: function (res) {
                     $(".nivaraLoader").hide();
                }
            });
        });
    });
</script>